### ISSUE TITLE
Créer page github

### ISSUE THREAD

**Issue by YoannDupont** [KenzaAHMIA/PROJET-FASTFOOD#1]
Bonjour,

Il faudrait créer une page github pour votre projet. Cela facilitera l'ajout des tableaux.

**Comment by KenzaAHMIA** [comment]
Bonjour,

C'est à dire ?

**Comment by YoannDupont** [comment]
Bonjour,

Le rendu final pour le groupe implique de créer une page github pour le projet où vous allez mettre, entre autres, les tableaux relatifs à votre corpus (codes HTTP, URL, encodage, etc).

**Comment by KenzaAHMIA** [comment]
Bonsoir,

Nous ferons ça. Je vous remercie.
